import 'package:flutter/material.dart';

class arrData {
  /// Intro Page Data
  static final List<Map<String , dynamic>> mIntroData = [
    {
      'image' : "assets/images/bg_img1.png",
      'imgtext' : 'Skip',
      'titie1' : "ज़िंदगी छोटी है बीरा ओर\n दुनिया ",
      'titie2' : "घनी मोटी",
      'subtitle' : 'At Friends tours and travel, we customize reliable and trutworthy educational tours to destinations all over the world',
      'buttonText' : 'Get Started',
    },
    {
      'image' : "assets/images/bg_img3.png",
      'imgtext' : 'Skip',
      'titie1' : "It’s a big world out there go ",
      'titie2' : "explore",
      'subtitle' : 'To get the best of your adventure you just need to leave and go where you like. we are waiting for you',
      'buttonText' : 'Next',
    },
    {
      'image' : "assets/images/bg_img2.png",
      'imgtext' : 'Skip',
      'titie1' : "People don’t take trips, trips take",
      'titie2' : "people",
      'subtitle' : 'To get the best of your adventure you just need to leave and go where you like. we are waiting for you',
      'buttonText' : 'Next',
    },
  ];


  /// Home Page Content
  static final List<Map<String, dynamic>> mPlacesData = [
    {
      'Places_title' : 'Popular Destinations',
      'Popular Places' : [
        {
          'image' : "assets/images/bg_WorldPopular1.png",
          'icon1' : "assets/images/icon_bookmark.png",
          'title' : "Eiffel Tower",
          'icon2' : Icons.star,
          'icon text' : "4.7",
          'icon3' : "assets/images/icon_location.png",
          'sub title' : "Paris,France",
          'profile1' : "assets/images/bg_Ellipse 1.png",
          'profile2' : "assets/images/bg_Ellipse 2.png",
          'profile3' : "assets/images/bg_Ellipse 3.png",
          'profile4' : "assets/images/Group 11.png",
          'background image' : 'assets/images/bg_WorldPopular1.png',
          'header content1' : Icons.arrow_back_ios,
          'header text' : 'Details',
          'header content2' : 'assets/images/icon_bookmark.png',
          'dash icon' : 'assets/images/icon_dash.png',
          'sub title inside' : 'Paris , France',
          'title inside' : 'Eieffel Tower',
          'profile image' : 'assets/images/bg_Ellipse 1.png',
          'location icon' : 'assets/images/icon_location.png',
          'location text' : 'Paris',
          'rating icon' : Icons.star,
          'rating text' : '4.7',
          'review text' : '(2500)',
          'money text' : '\$59/',
          'over person text' : 'Person',
          'image 1' : 'assets/images/bg_places1.png',
          'image 2' : 'assets/images/bg_places2.png',
          'image 3' : 'assets/images/bg_places3.png',
          'image 4' : 'assets/images/bg_places4.png',
          'image 5' : 'assets/images/bg_places5.png',
          'about us heading' : 'About Destination',
          'about us text1' : 'You will get a complete travel package on the beaches. Packages in the form of airline tickets, recommended Hotel rooms, Transportation, Have you ever been on holiday to the Greek ETC...',
          'about us text2' : 'Read me',
        },
        {
          'image' : "assets/images/bg_WorldPopular2.png",
          'icon1' : "assets/images/icon_bookmark.png",
          'title' : "london",
          'icon2' : Icons.star,
          'icon text' : "4.7",
          'icon3' : "assets/images/icon_location.png",
          'sub title' : "Big Ben",
          'profile1' : "assets/images/bg_Ellipse 1.png",
          'profile2' : "assets/images/bg_Ellipse 2.png",
          'profile3' : "assets/images/bg_Ellipse 3.png",
          'profile4' : "assets/images/Group 11.png",
          'background image' : 'assets/images/bg_WorldPopular2.png',
          'header content1' : Icons.arrow_back_ios,
          'header text' : 'Details',
          'header content2' : 'assets/images/icon_bookmark.png',
          'dash icon' : 'assets/images/icon_dash.png',
          'sub title inside' : 'London',
          'title inside' : 'Big Ben',
          'profile image' : 'assets/images/bg_Ellipse 1.png',
          'location icon' : 'assets/images/icon_location.png',
          'location text' : 'United Kingdom',
          'rating icon' : Icons.star,
          'rating text' : '4.0',
          'review text' : '(2500)',
          'money text' : '\$59/',
          'over person text' : 'Person',
          'image 1' : 'assets/images/bg_places1.png',
          'image 2' : 'assets/images/bg_places2.png',
          'image 3' : 'assets/images/bg_places3.png',
          'image 4' : 'assets/images/bg_places4.png',
          'image 5' : 'assets/images/bg_places5.png',
          'about us heading' : 'About Destination',
          'about us text1' : 'You will get a complete travel package on the beaches. Packages in the form of airline tickets, recommended Hotel rooms, Transportation, Have you ever been on holiday to the Greek ETC...',
          'about us text2' : 'Read me',
        },
        {
          'image' : "assets/images/bg_WorldPopular3.png",
          'icon1' : "assets/images/icon_bookmark.png",
          'title' : "Udaipur",
          'icon2' : Icons.star,
          'icon text' : "4.7",
          'icon3' : "assets/images/icon_location.png",
          'sub title' : "India",
          'profile1' : "assets/images/bg_Ellipse 1.png",
          'profile2' : "assets/images/bg_Ellipse 2.png",
          'profile3' : "assets/images/bg_Ellipse 3.png",
          'profile4' : "assets/images/Group 11.png",
          'background image' : 'assets/images/bg_WorldPopular3.png',
          'header content1' : Icons.arrow_back_ios,
          'header text' : 'Details',
          'header content2' : 'assets/images/icon_bookmark.png',
          'dash icon' : 'assets/images/icon_dash.png',
          'sub title inside' : 'Udaipur',
          'title inside' : 'Fateh Sagar Lake',
          'profile image' : 'assets/images/bg_Ellipse 1.png',
          'location icon' : 'assets/images/icon_location.png',
          'location text' : 'India',
          'rating icon' : Icons.star,
          'rating text' : '4.7',
          'review text' : '(2500)',
          'money text' : '\$59/',
          'over person text' : 'Person',
          'image 1' : 'assets/images/bg_places1.png',
          'image 2' : 'assets/images/bg_places2.png',
          'image 3' : 'assets/images/bg_places3.png',
          'image 4' : 'assets/images/bg_places4.png',
          'image 5' : 'assets/images/bg_places5.png',
          'about us heading' : 'About Destination',
          'about us text1' : 'You will get a complete travel package on the beaches. Packages in the form of airline tickets, recommended Hotel rooms, Transportation, Have you ever been on holiday to the Greek ETC...',
          'about us text2' : 'Read me',
        },
        {
          'image' : "assets/images/bg_WorldPopular5.png",
          'icon1' : "assets/images/icon_bookmark.png",
          'title' : "Santorini",
          'icon2' : Icons.star,
          'icon text' : "4.7",
          'icon3' : "assets/images/icon_location.png",
          'sub title' : "Greece",
          'profile1' : "assets/images/bg_Ellipse 1.png",
          'profile2' : "assets/images/bg_Ellipse 2.png",
          'profile3' : "assets/images/bg_Ellipse 3.png",
          'profile4' : "assets/images/Group 11.png",
          'background image' : 'assets/images/bg_WorldPopular5.png',
          'header content1' : Icons.arrow_back_ios,
          'header text' : 'Details',
          'header content2' : 'assets/images/icon_bookmark.png',
          'dash icon' : 'assets/images/icon_dash.png',
          'sub title inside' : 'Greece , Europe',
          'title inside' : 'Santorini',
          'profile image' : 'assets/images/bg_Ellipse 1.png',
          'location icon' : 'assets/images/icon_location.png',
          'location text' : 'Greece',
          'rating icon' : Icons.star,
          'rating text' : '4.7',
          'review text' : '(2500)',
          'money text' : '\$59/',
          'over person text' : 'Person',
          'image 1' : 'assets/images/bg_places1.png',
          'image 2' : 'assets/images/bg_places2.png',
          'image 3' : 'assets/images/bg_places3.png',
          'image 4' : 'assets/images/bg_places4.png',
          'image 5' : 'assets/images/bg_places5.png',
          'about us heading' : 'About Destination',
          'about us text1' : 'You will get a complete travel package on the beaches. Packages in the form of airline tickets, recommended Hotel rooms, Transportation, Have you ever been on holiday to the Greek ETC...',
          'about us text2' : 'Read me',
        },
      ],

    },
    {
      'Places_title' : 'India',
      'Popular Places' : [
        {
          'image' : "assets/images/bg_WorldPopular3.png",
          'icon1' : "assets/images/icon_bookmark.png",
          'title' : "Udaipur",
          'icon2' : Icons.star,
          'icon text' : "4.7",
          'icon3' : "assets/images/icon_location.png",
          'sub title' : "India",
          'profile1' : "assets/images/bg_Ellipse 1.png",
          'profile2' : "assets/images/bg_Ellipse 2.png",
          'profile3' : "assets/images/bg_Ellipse 3.png",
          'profile4' : "assets/images/Group 11.png",
          'background image' : 'assets/images/bg_WorldPopular3.png',
          'header content1' : Icons.arrow_back_ios,
          'header text' : 'Details',
          'header content2' : 'assets/images/icon_bookmark.png',
          'dash icon' : 'assets/images/icon_dash.png',
          'sub title inside' : 'Udaipur',
          'title inside' : 'Fateh Sagar Lake',
          'profile image' : 'assets/images/bg_Ellipse 1.png',
          'location icon' : 'assets/images/icon_location.png',
          'location text' : 'India',
          'rating icon' : Icons.star,
          'rating text' : '4.7',
          'review text' : '(2500)',
          'money text' : '\$59/',
          'over person text' : 'Person',
          'image 1' : 'assets/images/bg_places1.png',
          'image 2' : 'assets/images/bg_places2.png',
          'image 3' : 'assets/images/bg_places3.png',
          'image 4' : 'assets/images/bg_places4.png',
          'image 5' : 'assets/images/bg_places5.png',
          'about us heading' : 'About Destination',
          'about us text1' : 'You will get a complete travel package on the beaches. Packages in the form of airline tickets, recommended Hotel rooms, Transportation, Have you ever been on holiday to the Greek ETC...',
          'about us text2' : 'Read me',
        },
        {'image' : "assets/images/bg_PosterJaipur.png",
          'icon1' : "assets/images/icon_bookmark.png",
          'title' : "Jaipur",
          'icon2' : Icons.star,
          'icon text' : "4.3",
          'icon3' : "assets/images/icon_location.png",
          'sub title' : "Rajasthan",
          'profile1' : "assets/images/bg_Ellipse 1.png",
          'profile2' : "assets/images/bg_Ellipse 2.png",
          'profile3' : "assets/images/bg_Ellipse 3.png",
          'profile4' : "assets/images/Group 11.png",
          'background image' : 'assets/images/bg_WorldPopular3.png',
          'header content1' : Icons.arrow_back_ios,
          'header text' : 'Details',
          'header content2' : 'assets/images/icon_bookmark.png',
          'dash icon' : 'assets/images/icon_dash.png',
          'sub title inside' : 'Jaipur',
          'title inside' : 'Amer Fort',
          'profile image' : 'assets/images/bg_Ellipse 1.png',
          'location icon' : 'assets/images/icon_location.png',
          'location text' : 'India',
          'rating icon' : Icons.star,
          'rating text' : '4.3',
          'review text' : '(2500)',
          'money text' : '\$59/',
          'over person text' : 'Person',
          'image 1' : 'assets/images/bg_places1.png',
          'image 2' : 'assets/images/bg_places2.png',
          'image 3' : 'assets/images/bg_places3.png',
          'image 4' : 'assets/images/bg_places4.png',
          'image 5' : 'assets/images/bg_places5.png',
          'about us heading' : 'About Destination',
          'about us text1' : 'You will get a complete travel package on the beaches. Packages in the form of airline tickets, recommended Hotel rooms, Transportation, Have you ever been on holiday to the Greek ETC...',
          'about us text2' : 'Read me',
        },
        {'image' : "assets/images/bg_PosterJodhpur.jpg",
          'icon1' : "assets/images/icon_bookmark.png",
          'title' : "Jodhpur",
          'icon2' : Icons.star,
          'icon text' : "4.3",
          'icon3' : "assets/images/icon_location.png",
          'sub title' : "Rajasthan",
          'profile1' : "assets/images/bg_Ellipse 1.png",
          'profile2' : "assets/images/bg_Ellipse 2.png",
          'profile3' : "assets/images/bg_Ellipse 3.png",
          'profile4' : "assets/images/Group 11.png",
          'background image' : 'assets/images/bg_WorldPopular3.png',
          'header content1' : Icons.arrow_back_ios,
          'header text' : 'Details',
          'header content2' : 'assets/images/icon_bookmark.png',
          'dash icon' : 'assets/images/icon_dash.png',
          'sub title inside' : 'Jaipur',
          'title inside' : 'Amer Fort',
          'profile image' : 'assets/images/bg_Ellipse 1.png',
          'location icon' : 'assets/images/icon_location.png',
          'location text' : 'India',
          'rating icon' : Icons.star,
          'rating text' : '4.3',
          'review text' : '(2500)',
          'money text' : '\$59/',
          'over person text' : 'Person',
          'image 1' : 'assets/images/bg_places1.png',
          'image 2' : 'assets/images/bg_places2.png',
          'image 3' : 'assets/images/bg_places3.png',
          'image 4' : 'assets/images/bg_places4.png',
          'image 5' : 'assets/images/bg_places5.png',
          'about us heading' : 'About Destination',
          'about us text1' : 'You will get a complete travel package on the beaches. Packages in the form of airline tickets, recommended Hotel rooms, Transportation, Have you ever been on holiday to the Greek ETC...',
          'about us text2' : 'Read me',
        },
        {'image' : "assets/images/bg_PosterTungnath.jpg",
          'icon1' : "assets/images/icon_bookmark.png",
          'title' : "Tungnath",
          'icon2' : Icons.star,
          'icon text' : "4.3",
          'icon3' : "assets/images/icon_location.png",
          'sub title' : "Uttrakhand",
          'profile1' : "assets/images/bg_Ellipse 1.png",
          'profile2' : "assets/images/bg_Ellipse 2.png",
          'profile3' : "assets/images/bg_Ellipse 3.png",
          'profile4' : "assets/images/Group 11.png",
          'background image' : 'assets/images/bg_WorldPopular3.png',
          'header content1' : Icons.arrow_back_ios,
          'header text' : 'Details',
          'header content2' : 'assets/images/icon_bookmark.png',
          'dash icon' : 'assets/images/icon_dash.png',
          'sub title inside' : 'Chopta Village',
          'title inside' : 'Tungnath',
          'profile image' : 'assets/images/bg_Ellipse 1.png',
          'location icon' : 'assets/images/icon_location.png',
          'location text' : 'India',
          'rating icon' : Icons.star,
          'rating text' : '4.3',
          'review text' : '(2500)',
          'money text' : '\$59/',
          'over person text' : 'Person',
          'image 1' : 'assets/images/bg_places1.png',
          'image 2' : 'assets/images/bg_places2.png',
          'image 3' : 'assets/images/bg_places3.png',
          'image 4' : 'assets/images/bg_places4.png',
          'image 5' : 'assets/images/bg_places5.png',
          'about us heading' : 'About Destination',
          'about us text1' : 'You will get a complete travel package on the beaches. Packages in the form of airline tickets, recommended Hotel rooms, Transportation, Have you ever been on holiday to the Greek ETC...',
          'about us text2' : 'Read me',
        },
      ],

    },
    {
      'Places_title' : 'Other Countries',
      'Popular Places' :[
        {
          'image' : "assets/images/bg_WorldPopular1.png",
          'icon1' : "assets/images/icon_bookmark.png",
          'title' : "Paris",
          'icon2' : Icons.star,
          'icon text' : "4.7",
          'icon3' : "assets/images/icon_location.png",
          'sub title' : "France",
          'profile1' : "assets/images/bg_Ellipse 1.png",
          'profile2' : "assets/images/bg_Ellipse 2.png",
          'profile3' : "assets/images/bg_Ellipse 3.png",
          'profile4' : "assets/images/Group 11.png",
          'background image' : 'assets/images/bg_WorldPopular1.png',
          'header content1' : Icons.arrow_back_ios,
          'header text' : 'Details',
          'header content2' : 'assets/images/icon_bookmark.png',
          'dash icon' : 'assets/images/icon_dash.png',
          'sub title inside' : 'Paris , France',
          'title inside' : 'Eieffel Tower',
          'profile image' : 'assets/images/bg_Ellipse 1.png',
          'location icon' : 'assets/images/icon_location.png',
          'location text' : 'Paris',
          'rating icon' : Icons.star,
          'rating text' : '4.7',
          'review text' : '(2500)',
          'money text' : '\$59/',
          'over person text' : 'Person',
          'image 1' : 'assets/images/bg_places1.png',
          'image 2' : 'assets/images/bg_places2.png',
          'image 3' : 'assets/images/bg_places3.png',
          'image 4' : 'assets/images/bg_places4.png',
          'image 5' : 'assets/images/bg_places5.png',
          'about us heading' : 'About Destination',
          'about us text1' : 'You will get a complete travel package on the beaches. Packages in the form of airline tickets, recommended Hotel rooms, Transportation, Have you ever been on holiday to the Greek ETC...',
          'about us text2' : 'Read me',
        },
        {
          'image' : "assets/images/bg_WorldPopular2.png",
          'icon1' : "assets/images/icon_bookmark.png",
          'title' : "london",
          'icon2' : Icons.star,
          'icon text' : "4.7",
          'icon3' : "assets/images/icon_location.png",
          'sub title' : "Big Ben",
          'profile1' : "assets/images/bg_Ellipse 1.png",
          'profile2' : "assets/images/bg_Ellipse 2.png",
          'profile3' : "assets/images/bg_Ellipse 3.png",
          'profile4' : "assets/images/Group 11.png",
          'background image' : 'assets/images/bg_WorldPopular2.png',
          'header content1' : Icons.arrow_back_ios,
          'header text' : 'Details',
          'header content2' : 'assets/images/icon_bookmark.png',
          'dash icon' : 'assets/images/icon_dash.png',
          'sub title inside' : 'London',
          'title inside' : 'Big Ben',
          'profile image' : 'assets/images/bg_Ellipse 1.png',
          'location icon' : 'assets/images/icon_location.png',
          'location text' : 'United Kingdom',
          'rating icon' : Icons.star,
          'rating text' : '4.0',
          'review text' : '(2500)',
          'money text' : '\$59/',
          'over person text' : 'Person',
          'image 1' : 'assets/images/bg_places1.png',
          'image 2' : 'assets/images/bg_places2.png',
          'image 3' : 'assets/images/bg_places3.png',
          'image 4' : 'assets/images/bg_places4.png',
          'image 5' : 'assets/images/bg_places5.png',
          'about us heading' : 'About Destination',
          'about us text1' : 'You will get a complete travel package on the beaches. Packages in the form of airline tickets, recommended Hotel rooms, Transportation, Have you ever been on holiday to the Greek ETC...',
          'about us text2' : 'Read me',
        },
        {
          'image' : "assets/images/bg_WorldPopular3.png",
          'icon1' : "assets/images/icon_bookmark.png",
          'title' : "Udaipur",
          'icon2' : Icons.star,
          'icon text' : "4.7",
          'icon3' : "assets/images/icon_location.png",
          'sub title' : "India",
          'profile1' : "assets/images/bg_Ellipse 1.png",
          'profile2' : "assets/images/bg_Ellipse 2.png",
          'profile3' : "assets/images/bg_Ellipse 3.png",
          'profile4' : "assets/images/Group 11.png",
          'background image' : 'assets/images/bg_WorldPopular3.png',
          'header content1' : Icons.arrow_back_ios,
          'header text' : 'Details',
          'header content2' : 'assets/images/icon_bookmark.png',
          'dash icon' : 'assets/images/icon_dash.png',
          'sub title inside' : 'Udaipur',
          'title inside' : 'Fateh Sagar Lake',
          'profile image' : 'assets/images/bg_Ellipse 1.png',
          'location icon' : 'assets/images/icon_location.png',
          'location text' : 'India',
          'rating icon' : Icons.star,
          'rating text' : '4.7',
          'review text' : '(2500)',
          'money text' : '\$59/',
          'over person text' : 'Person',
          'image 1' : 'assets/images/bg_places1.png',
          'image 2' : 'assets/images/bg_places2.png',
          'image 3' : 'assets/images/bg_places3.png',
          'image 4' : 'assets/images/bg_places4.png',
          'image 5' : 'assets/images/bg_places5.png',
          'about us heading' : 'About Destination',
          'about us text1' : 'You will get a complete travel package on the beaches. Packages in the form of airline tickets, recommended Hotel rooms, Transportation, Have you ever been on holiday to the Greek ETC...',
          'about us text2' : 'Read me',
        },
        {'image' : "assets/images/bg_WorldPopular6.png",
          'icon1' : "assets/images/icon_bookmark.png",
          'title' : "Kyoto",
          'icon2' : Icons.star,
          'icon text' : "4.3",
          'icon3' : "assets/images/icon_location.png",
          'sub title' : "Japan",
          'profile1' : "assets/images/bg_Ellipse 1.png",
          'profile2' : "assets/images/bg_Ellipse 2.png",
          'profile3' : "assets/images/bg_Ellipse 3.png",
          'profile4' : "assets/images/Group 11.png",
          'background image' : 'assets/images/bg_WorldPopular6.png',
          'header content1' : Icons.arrow_back_ios,
          'header text' : 'Details',
          'header content2' : 'assets/images/icon_bookmark.png',
          'dash icon' : 'assets/images/icon_dash.png',
          'sub title inside' : 'Japan',
          'title inside' : 'Kyoto',
          'profile image' : 'assets/images/bg_Ellipse 1.png',
          'location icon' : 'assets/images/icon_location.png',
          'location text' : 'Japan',
          'rating icon' : Icons.star,
          'rating text' : '4.3',
          'review text' : '(2500)',
          'money text' : '\$59/',
          'over person text' : 'Person',
          'image 1' : 'assets/images/bg_places1.png',
          'image 2' : 'assets/images/bg_places2.png',
          'image 3' : 'assets/images/bg_places3.png',
          'image 4' : 'assets/images/bg_places4.png',
          'image 5' : 'assets/images/bg_places5.png',
          'about us heading' : 'About Destination',
          'about us text1' : 'You will get a complete travel package on the beaches. Packages in the form of airline tickets, recommended Hotel rooms, Transportation, Have you ever been on holiday to the Greek ETC...',
          'about us text2' : 'Read me',
        },
      ],
    },
  ];

  /// Detail Page Description
  static final List<Map<String,dynamic>> mPlacesDescriptions = [
    {
      'background image' : 'assets/images/bg_WorldPopular1.png',
      'header content1' : Icons.arrow_back_ios,
      'header text' : 'Details',
      'header content2' : 'assets/images/icon_bookmark.png',
      'dash icon' : 'assets/images/icon_dash.png',
      'sub title' : 'Paris , France',
      'title' : 'Eieffel Tower',
      'profile image' : 'assets/images/bg_Ellipse 1.png',
      'location icon' : 'assets/images/icon_location.png',
      'location text' : 'Paris',
      'rating icon' : Icons.star,
      'rating text' : '4.7',
      'review text' : '(2500)',
      'money text' : '\$59/',
      'over person text' : 'Person',
      'image 1' : 'assets/images/bg_places1.png',
      'image 2' : 'assets/images/bg_places2.png',
      'image 3' : 'assets/images/bg_places3.png',
      'image 4' : 'assets/images/bg_places4.png',
      'image 5' : 'assets/images/bg_places5.png',
      'about us heading' : 'About Destination',
      'about us text1' : 'You will get a complete travel package on the beaches. Packages in the form of airline tickets, recommended Hotel rooms, Transportation, Have you ever been on holiday to the Greek ETC...',
      'about us text2' : 'Read me',
    },
    {
      'background image' : 'assets/images/bg_WorldPopular2.png',
      'header content1' : Icons.arrow_back_ios,
      'header text' : 'Details',
      'header content2' : 'assets/images/icon_bookmark.png',
      'dash icon' : 'assets/images/icon_dash.png',
      'sub title' : 'London',
      'title' : 'Big Ben',
      'profile image' : 'assets/images/bg_Ellipse 1.png',
      'location icon' : 'assets/images/icon_location.png',
      'location text' : 'United Kingdom',
      'rating icon' : Icons.star,
      'rating text' : '4.0',
      'review text' : '(2500)',
      'money text' : '\$59/',
      'over person text' : 'Person',
      'image 1' : 'assets/images/bg_places1.png',
      'image 2' : 'assets/images/bg_places2.png',
      'image 3' : 'assets/images/bg_places3.png',
      'image 4' : 'assets/images/bg_places4.png',
      'image 5' : 'assets/images/bg_places5.png',
      'about us heading' : 'About Destination',
      'about us text1' : 'You will get a complete travel package on the beaches. Packages in the form of airline tickets, recommended Hotel rooms, Transportation, Have you ever been on holiday to the Greek ETC...',
      'about us text2' : 'Read me',
    },
    {
      'background image' : 'assets/images/bg_WorldPopular3.png',
      'header content1' : Icons.arrow_back_ios,
      'header text' : 'Details',
      'header content2' : 'assets/images/icon_bookmark.png',
      'dash icon' : 'assets/images/icon_dash.png',
      'sub title' : 'Udaipur',
      'title' : 'Fateh Sagar Lake',
      'profile image' : 'assets/images/bg_Ellipse 1.png',
      'location icon' : 'assets/images/icon_location.png',
      'location text' : 'India',
      'rating icon' : Icons.star,
      'rating text' : '4.7',
      'review text' : '(2500)',
      'money text' : '\$59/',
      'over person text' : 'Person',
      'image 1' : 'assets/images/bg_places1.png',
      'image 2' : 'assets/images/bg_places2.png',
      'image 3' : 'assets/images/bg_places3.png',
      'image 4' : 'assets/images/bg_places4.png',
      'image 5' : 'assets/images/bg_places5.png',
      'about us heading' : 'About Destination',
      'about us text1' : 'You will get a complete travel package on the beaches. Packages in the form of airline tickets, recommended Hotel rooms, Transportation, Have you ever been on holiday to the Greek ETC...',
      'about us text2' : 'Read me',
    }
  ];

  /// Notification Panel
  static final List<Map<String, dynamic>> mRecentNotification =[

    {
      'list1RecentTab' : [
        {
          'profile' : 'assets/images/bg_Ellipse 1.png',
          'title' : 'Super Offer',
          'sub title' : 'get 60% off on first booking',
          'date' : 'Sun, 12:40pm',
        },
        {
          'profile' : 'assets/images/icon_Red_bus.png',
          'title' : 'Red bus',
          'sub title' : 'get 20% off on any ride',
          'date' : 'Sun, 2:14pm',
        },
        {
          'profile' : 'assets/images/icon_makemytrip.png',
          'title' : 'Make my trip',
          'sub title' : 'Make your trip joyful with us',
          'date' : 'Sun, 10:14pm',
        },
        {
          'profile' : 'assets/images/icon_flightbooking.png',
          'title' : 'Ixigo',
          'sub title' : 'Book your flights with single tap',
          'date' : 'Sun, 10:14pm',
        },
      ]
    },
    /*{
      'list1EarlierTab' : [
        {
          'profile' : 'assets/images/bg_Ellipse 1.png',
          'title' : 'Offer',
          'sub title' : 'get 60% off on first booking',
          'date' : 'Sat, 12:40pm',
        },
        {
          'profile' : 'assets/images/icon_Red_bus.png',
          'title' : 'Red bus',
          'sub title' : 'get 20% off on any ride',
          'date' : 'Wed, 2:14pm',
        },
        {
          'profile' : 'assets/images/icon_makemytrip.png',
          'title' : 'Make my trip',
          'sub title' : 'Make your trip joyful with us',
          'date' : 'Thur, 10:14pm',
        },
        {
          'profile' : 'assets/images/icon_flightbooking.png',
          'title' : 'Ixigo',
          'sub title' : 'Book your flights with single tap',
          'date' : 'Sat, 10:14pm',
        },
      ]
    },*/
  ];

  /// Popular Places
  static final List<Map<String, dynamic>> mPopularplacesData = [
    {
      'background image' : 'assets/images/bg_WorldPopular1.png',
      'stack icon' : 'assets/images/icon_heart.png',
      'text' : 'Eieffel Tower',
      'location icon' : 'assets/images/icon_location.png',
      'location text' : 'Paris , France',
      'review icon' : Icons.star,
      'Review text' : '4.7',
      'money text' : '\$459/',
      'Person text' : 'Person',
      'background image inside' : 'assets/images/bg_WorldPopular1.png',
      'header content1' : Icons.arrow_back_ios,
      'header text' : 'Details',
      'header content2' : 'assets/images/icon_bookmark.png',
      'dash icon' : 'assets/images/icon_dash.png',
      'sub title' : 'Paris , France',
      'title' : 'Eieffel Tower',
      'profile image' : 'assets/images/bg_Ellipse 1.png',
      'location icon inside' : 'assets/images/icon_location.png',
      'location text inside' : 'Paris',
      'rating icon' : Icons.star,
      'rating text' : '4.7',
      'review text' : '(2500)',
      'money text inside' : '\$59/',
      'over person text' : 'Person',
      'image 1' : 'assets/images/bg_places1.png',
      'image 2' : 'assets/images/bg_places2.png',
      'image 3' : 'assets/images/bg_places3.png',
      'image 4' : 'assets/images/bg_places4.png',
      'image 5' : 'assets/images/bg_places5.png',
      'about us heading' : 'About Destination',
      'about us text1' : 'You will get a complete travel package on the beaches. Packages in the form of airline tickets, recommended Hotel rooms, Transportation, Have you ever been on holiday to the Greek ETC...',
      'about us text2' : 'Read me',
    },
    {
      'background image' : 'assets/images/bg_WorldPopular2.png',
      'stack icon' : 'assets/images/icon_heart.png',
      'text' : 'Big-Ben',
      'location icon' : 'assets/images/icon_location.png',
      'location text' : 'London',
      'review icon' : Icons.star,
      'Review text' : '4.7',
      'money text' : '\$459/',
      'Person text' : 'Person',
      'background image inside' : 'assets/images/bg_WorldPopular2.png',
      'header content1' : Icons.arrow_back_ios,
      'header text' : 'Details',
      'header content2' : 'assets/images/icon_bookmark.png',
      'dash icon' : 'assets/images/icon_dash.png',
      'sub title' : 'London',
      'title' : 'Big Ben',
      'profile image' : 'assets/images/bg_Ellipse 1.png',
      'location icon inside' : 'assets/images/icon_location.png',
      'location text inside' : 'United Kingdom',
      'rating icon' : Icons.star,
      'rating text' : '4.0',
      'review text' : '(2500)',
      'money text inside' : '\$59/',
      'over person text' : 'Person',
      'image 1' : 'assets/images/bg_places1.png',
      'image 2' : 'assets/images/bg_places2.png',
      'image 3' : 'assets/images/bg_places3.png',
      'image 4' : 'assets/images/bg_places4.png',
      'image 5' : 'assets/images/bg_places5.png',
      'about us heading' : 'About Destination',
      'about us text1' : 'You will get a complete travel package on the beaches. Packages in the form of airline tickets, recommended Hotel rooms, Transportation, Have you ever been on holiday to the Greek ETC...',
      'about us text2' : 'Read me',
    },
    {
      'background image' : 'assets/images/bg_WorldPopular3.png',
      'stack icon' : 'assets/images/icon_heart.png',
      'text' : 'Fateh Sagar Lake',
      'location icon' : 'assets/images/icon_location.png',
      'location text' : 'Rajasthan ,India',
      'review icon' : Icons.star,
      'Review text' : '4.7',
      'money text' : '\$459/',
      'Person text' : 'Person',
      'background image inside' : 'assets/images/bg_WorldPopular3.png',
      'header content1' : Icons.arrow_back_ios,
      'header text' : 'Details',
      'header content2' : 'assets/images/icon_bookmark.png',
      'dash icon' : 'assets/images/icon_dash.png',
      'sub title' : 'Udaipur',
      'title' : 'Fateh Sagar Lake',
      'profile image' : 'assets/images/bg_Ellipse 1.png',
      'location icon inside' : 'assets/images/icon_location.png',
      'location text inside' : 'India',
      'rating icon' : Icons.star,
      'rating text' : '4.7',
      'review text' : '(2500)',
      'money text inside' : '\$59/',
      'over person text' : 'Person',
      'image 1' : 'assets/images/bg_places1.png',
      'image 2' : 'assets/images/bg_places2.png',
      'image 3' : 'assets/images/bg_places3.png',
      'image 4' : 'assets/images/bg_places4.png',
      'image 5' : 'assets/images/bg_places5.png',
      'about us heading' : 'About Destination',
      'about us text1' : 'You will get a complete travel package on the beaches. Packages in the form of airline tickets, recommended Hotel rooms, Transportation, Have you ever been on holiday to the Greek ETC...',
      'about us text2' : 'Read me',
    },
    {
      'background image' : 'assets/images/bg_WorldPopular4.png',
      'stack icon' : 'assets/images/icon_heart.png',
      'text' : 'Rome',
      'location icon' : 'assets/images/icon_location.png',
      'location text' : 'Rome ,Italy',
      'review icon' : Icons.star,
      'Review text' : '4.7',
      'money text' : '\$459/',
      'Person text' : 'Person',
      'background image inside' : 'assets/images/bg_WorldPopular4.png',
      'header content1' : Icons.arrow_back_ios,
      'header text' : 'Details',
      'header content2' : 'assets/images/icon_bookmark.png',
      'dash icon' : 'assets/images/icon_dash.png',
      'sub title' : 'Rome ,Italy',
      'title' : 'The Colosseum',
      'profile image' : 'assets/images/bg_Ellipse 1.png',
      'location icon inside' : 'assets/images/icon_location.png',
      'location text inside' : 'Italy',
      'rating icon' : Icons.star,
      'rating text' : '4.7',
      'review text' : '(2500)',
      'money text inside' : '\$59/',
      'over person text' : 'Person',
      'image 1' : 'assets/images/bg_places1.png',
      'image 2' : 'assets/images/bg_places2.png',
      'image 3' : 'assets/images/bg_places3.png',
      'image 4' : 'assets/images/bg_places4.png',
      'image 5' : 'assets/images/bg_places5.png',
      'about us heading' : 'About Destination',
      'about us text1' : 'You will get a complete travel package on the beaches. Packages in the form of airline tickets, recommended Hotel rooms, Transportation, Have you ever been on holiday to the Greek ETC...',
      'about us text2' : 'Read me',
    },
    {
      'background image' : 'assets/images/bg_PosterJodhpur.jpg',
      'stack icon' : 'assets/images/icon_heart.png',
      'text' : 'Blue City',
      'location icon' : 'assets/images/icon_location.png',
      'location text' : 'Jodhpur ,Rajastha',
      'review icon' : Icons.star,
      'Review text' : '5.0',
      'money text' : '\$459/',
      'Person text' : 'Person',
      'background image inside' : 'assets/images/bg_PosterJodhpur.jpg',
      'header content1' : Icons.arrow_back_ios,
      'header text' : 'Details',
      'header content2' : 'assets/images/icon_bookmark.png',
      'dash icon' : 'assets/images/icon_dash.png',
      'sub title' : 'Jodhpur',
      'title' : 'Pachetia hills',
      'profile image' : 'assets/images/bg_Ellipse 1.png',
      'location icon inside' : 'assets/images/icon_location.png',
      'location text inside' : 'India',
      'rating icon' : Icons.star,
      'rating text' : '4.7',
      'review text' : '(2500)',
      'money text inside' : '\$59/',
      'over person text' : 'Person',
      'image 1' : 'assets/images/bg_places1.png',
      'image 2' : 'assets/images/bg_places2.png',
      'image 3' : 'assets/images/bg_places3.png',
      'image 4' : 'assets/images/bg_places4.png',
      'image 5' : 'assets/images/bg_places5.png',
      'about us heading' : 'About Destination',
      'about us text1' : 'You will get a complete travel package on the beaches. Packages in the form of airline tickets, recommended Hotel rooms, Transportation, Have you ever been on holiday to the Greek ETC...',
      'about us text2' : 'Read me',
    },
    {
      'background image' : 'assets/images/bg_PosterTungnath.jpg',
      'stack icon' : 'assets/images/icon_heart.png',
      'text' : 'Tungnath Mahadev',
      'location icon' : 'assets/images/icon_location.png',
      'location text' : 'uttrakhand',
      'review icon' : Icons.star,
      'Review text' : '5.0',
      'money text' : '\$459/',
      'Person text' : 'Person',
      'background image inside' : 'assets/images/bg_PosterTungnath.jpg',
      'header content1' : Icons.arrow_back_ios,
      'header text' : 'Details',
      'header content2' : 'assets/images/icon_bookmark.png',
      'dash icon' : 'assets/images/icon_dash.png',
      'sub title' : 'Chopta',
      'title' : 'Tungnath',
      'profile image' : 'assets/images/bg_Ellipse 1.png',
      'location icon inside' : 'assets/images/icon_location.png',
      'location text inside' : 'India',
      'rating icon' : Icons.star,
      'rating text' : '4.7',
      'review text' : '(2500)',
      'money text inside' : '\$59/',
      'over person text' : 'Person',
      'image 1' : 'assets/images/bg_places1.png',
      'image 2' : 'assets/images/bg_places2.png',
      'image 3' : 'assets/images/bg_places3.png',
      'image 4' : 'assets/images/bg_places4.png',
      'image 5' : 'assets/images/bg_places5.png',
      'about us heading' : 'About Destination',
      'about us text1' : 'You will get a complete travel package on the beaches. Packages in the form of airline tickets, recommended Hotel rooms, Transportation, Have you ever been on holiday to the Greek ETC...',
      'about us text2' : 'Read me',
    },
  ];
}


